Feature theme switch
MergeMinds/mm-frontend pull request #3
Opened 2024-09-25 12:37 UTC by tolstovr

Created basic file structure and theme/contrast provider

2024-09-28 16:01 UTC, mchernigin commented
Не очень понимаю, почему оно не учитывает текущую тему системы. Я думаю, что стоит именно её использовать по умолчанию и опционально предоставлять возможность её перезаписать.

2024-09-28 16:30 UTC, tolstovr commented
Да, надо добавить, забыл

2024-09-28 17:38 UTC, mchernigin commented on src/lib/styles/theme.ts
> +export const themeColors = {
So this defines light and dark variants. But there are contrast variants? Or how do they work... I don't get it yet

2024-09-28 19:06 UTC, tolstovr commented on src/lib/styles/theme.ts
> +export const themeColors = {
Theme could be dark/light and normal/high-contrast. It's type has 2 properties

2024-09-29 11:49 UTC, vasthecat requested changes
Смена темы это хорошо, но она не меняется вместе с системой. Нужны три варианта - светлая, тёмная и системная. И в этой либе есть вот такое https://www.shadcn-svelte.com/docs/dark-mode/svelte. Есть ли какие-то причины почему это не было использовано?

2024-09-29 14:55 UTC, tolstovr commented
> И в этой либе есть вот такое https://www.shadcn-svelte.com/docs/dark-mode/svelte. Есть ли какие-то причины почему это не было использовано?

Есть одна причина - я не знал, что shadcn-ui такое умеет. В таком случае можно даже не заморачиваться с этим. Переделываю :)

2024-09-29 14:55 UTC, closed without merging